/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Vika } from "./Vika";
import { VikaCountArgs } from "./VikaCountArgs";
import { VikaFindManyArgs } from "./VikaFindManyArgs";
import { VikaFindUniqueArgs } from "./VikaFindUniqueArgs";
import { DeleteVikaArgs } from "./DeleteVikaArgs";
import { VikaService } from "../vika.service";
@graphql.Resolver(() => Vika)
export class VikaResolverBase {
  constructor(protected readonly service: VikaService) {}

  async _vikasMeta(
    @graphql.Args() args: VikaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Vika])
  async vikas(@graphql.Args() args: VikaFindManyArgs): Promise<Vika[]> {
    return this.service.vikas(args);
  }

  @graphql.Query(() => Vika, { nullable: true })
  async vika(@graphql.Args() args: VikaFindUniqueArgs): Promise<Vika | null> {
    const result = await this.service.vika(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Vika)
  async deleteVika(@graphql.Args() args: DeleteVikaArgs): Promise<Vika | null> {
    try {
      return await this.service.deleteVika(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Query(() => String)
  async TestAction(
    @graphql.Args("args")
    args: string
  ): Promise<string> {
    return this.service.TestAction(args);
  }
}
